language: java
jdk: oraclejdk8

deploy:
  -
    on:
      branch: release
    provider: bintray
    skip_cleanup: true
    file: src/main/resources/assembly/bintray-deploy.json
    user: ryanpadilha
    key: $BINTRAY_API_KEY